# Generated by Django 3.1 on 2020-08-16 11:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B11', models.BooleanField(default=True)),
                ('B12', models.BooleanField(default=True)),
                ('B13', models.BooleanField(default=True)),
                ('B14', models.BooleanField(default=True)),
                ('T11', models.BooleanField(default=True)),
                ('T12', models.BooleanField(default=True)),
                ('T13', models.BooleanField(default=True)),
                ('T14', models.BooleanField(default=True)),
                ('V11', models.BooleanField(default=True)),
                ('V12', models.BooleanField(default=True)),
                ('BT11', models.TextField(max_length=200)),
                ('BT12', models.TextField(max_length=200)),
                ('BT13', models.TextField(max_length=200)),
                ('BT14', models.TextField(max_length=200)),
                ('TT11', models.TextField(max_length=200)),
                ('TT12', models.TextField(max_length=200)),
                ('TT13', models.TextField(max_length=200)),
                ('TT14', models.TextField(max_length=200)),
                ('VT11', models.TextField(max_length=200)),
                ('VT12', models.TextField(max_length=200)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
    ]
