# Generated by Django 3.1 on 2020-08-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200816_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='BT11',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='BT12',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='BT13',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='BT14',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='TT11',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='TT12',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='TT13',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='TT14',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='VT11',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='VT12',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
